export const storeData = [
    {
        id : 1,
        title : 'Iphone -Black',
        img : 'https://th.bing.com/th/id/OIP.9VeZzavJDoJjqwAckXnf9wHaFj?w=207&h=180&c=7&r=0&o=5&pid=1.7',
        // img : 'https://th.bing.com/th/id/OIP.4fMbt3QcCffFTLNkI0km-gAAAA?w=115&h=180&c=7&r=0&o=5&pid=1.7',
        price : 20,
        company : 'Apple',
        info : 'The iPhone 13 and 13 Mini feature a 6-core CPU, 4-core GPU and 16-core Neural Engine, while the iPhone 13 Pro and 13 Pro Max feature a 5 core GPU. The iPhone 13 features a 6.1-inch (15 cm) display with Super Retina XDR OLED technology at a resolution of 2532×1170 pixels and a pixel density of about 460 PPI with a refresh rate of 60Hz.',
        inCart : false,
        count : 0,
        total : 0,
    },

    {
        id : 2,
        title : 'Huawei -P7',
        img : 'https://th.bing.com/th/id/OIP.3zzDgRfXEMC0HU5nvt2fbgHaHa?w=188&h=188&c=7&r=0&o=5&pid=1.7',
        // img : 'https://th.bing.com/th/id/OIP.4fMbt3QcCffFTLNkI0km-gAAAA?w=115&h=180&c=7&r=0&o=5&pid=1.7',
        price : 30,
        company : 'Huawei',
        info : 'Huawei Ascend P7 Android Smartphone was launched in May 2014. It is running on the HiSilicon Kirin 910T processor with Mali-450MP4 GPU. The phone has 2 GB RAM and 16 GB of internal storage which is expandable using microSD, up to 64 GB.',
        inCart : false,
        count : 0,
        total : 0,
    },


    {
        id : 3,
        title : 'Tecno Spark',
        img : 'https://th.bing.com/th/id/OIP.-sD1XMm18rmJ1zh3YE9XLQHaG9?w=208&h=196&c=7&r=0&o=5&pid=1.7',
        // img : 'https://th.bing.com/th/id/OIP.4fMbt3QcCffFTLNkI0km-gAAAA?w=115&h=180&c=7&r=0&o=5&pid=1.7',
        price : 40,
        company : 'Tecno mobile',
        info : "The Tecno Spark 8C features Unisoc T606 processor. It has 6.6 inches screen, for the graphics processing it has PowerVR IMG8322. Tecno Spark 8C runs on Android 11 Go operating system.",
        inCart : false,
        count : 0,
        total : 0,
    },

    {
        id : 4,
        title : 'Infinix Hot 10',
        img : 'https://th.bing.com/th/id/OIF.w6EuVvIRZBsnH0Z6qLmvfg?w=124&h=172&c=7&r=0&o=5&pid=1.7',
        // img : 'https://th.bing.com/th/id/OIP.4fMbt3QcCffFTLNkI0km-gAAAA?w=115&h=180&c=7&r=0&o=5&pid=1.7',
        price : 30,
        company : 'Infinix',
        info : "The Inifinix Hot 10's having 64 gigabytes of internal storage capacity which is enough to store ample data for daily usage. The smartphone also features a dedicated slot the can be used to increase the internal storage capacity of Hot 10 by Inifinix mobile phone a great deal.",
        inCart : false,
        count : 0,
        total : 0,
    },

    {
        id : 5,
        title : 'Xiaomi -Mi 11 pro',
        img : 'https://th.bing.com/th/id/OIP.4JPAazVO7CGVSnBajqUHmQHaHa?w=160&h=180&c=7&r=0&o=5&pid=1.7',
        // img : 'https://th.bing.com/th/id/OIP.4fMbt3QcCffFTLNkI0km-gAAAA?w=115&h=180&c=7&r=0&o=5&pid=1.7',
        price : 30,
        company : 'Xiaomi',
        info : "Xiaomi's Mi 11 smartphone use a 6.81-inch 1440x3200 120Hz 1,500 nits AMOLED display, a Qualcomm Snapdragon 888 chipset, 8/12 GB of RAM, 128/256 GB of storage, 5G connectivity and a triple camera setup",
        inCart : false,
        count : 0,
        total : 0,
    },

    {
        id : 6,
        title : 'Samsung -S10',
        img : 'https://th.bing.com/th?q=Samsung+10&w=120&h=120&c=1&rs=1&qlt=90&cb=1&pid=InlineBlock&mkt=en-WW&cc=GH&setlang=en&adlt=moderate&t=1&mw=247',
        // img : 'https://th.bing.com/th/id/OIP.4fMbt3QcCffFTLNkI0km-gAAAA?w=115&h=180&c=7&r=0&o=5&pid=1.7',
        price : 30,
        company : 'Samsung',
        info : " Samsung Galaxy S10 Released 2019, March 08 157g, 7.8mm thickness Android 9.0, up to Android 11, One UI 3.0 128GB/512GB storage, microSDXC 20% 10,811,354 hits",
        inCart : false,
        count : 0,
        total : 0,
    },

    {
        id : 7,
        title : 'HTC -Black',
        img : 'https://th.bing.com/th/id/OIP.ebRuUq1T2JrJrXiOddSqtwHaF2?w=237&h=188&c=7&r=0&o=5&pid=1.7',
        // img : 'https://th.bing.com/th/id/OIP.4fMbt3QcCffFTLNkI0km-gAAAA?w=115&h=180&c=7&r=0&o=5&pid=1.7',
        price : 30,
        company : 'htc',
        info : "The HTC 10 measures 145.9 x 71.9 x 9mm, while it weighs 161 grams. Additional HTC 10 Resources: The HTC 10 is quite probably the most premium smartphone HTC will release this year. This smartphone packs a lot of punch, the Sense UI has been improved, as is the camera, and the device offers premium build as well.",
        inCart : false,
        count : 0,
        total : 0,
    },

    {
        id : 8,
        title : 'Alcatel Z10',
        img : 'https://th.bing.com/th/id/OIP.WZVDJnhzY-df-Q6BLsm65QHaGH?w=259&h=214&c=7&r=0&o=5&pid=1.7',
        // img : 'https://th.bing.com/th/id/OIP.4fMbt3QcCffFTLNkI0km-gAAAA?w=115&h=180&c=7&r=0&o=5&pid=1.7',
        price : 30,
        company : 'alcatel',
        info : "Alcatel 1L (2021) has 32GB 2GB RAM of built-in memory. The main screen size is 6.1 inches, 89.8 cm2 with 720 x 1600 pixels, 20:9 ratio resolution. It has a 288 ppi density) ppi pixel density.",
        inCart : false,
        count : 0,
        total : 0,
    }

]

export const detailProduct = {
        id : 1,
        title : 'Samsung -Silver',
        // img : '/images/pic2.jpg',
        img : 'https://th.bing.com/th/id/OIP.4fMbt3QcCffFTLNkI0km-gAAAA?w=115&h=180&c=7&r=0&o=5&pid=1.7',
        price : 30,
        company : 'Samsung',
        info : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident, ea fugiat inventore rem recusandae mollitia reprehenderit, ipsa modi accusamus numquam exercitationem, nesciunt quia impedit dicta! Natus quos placeat et consequuntur!',
        inCart : false,
        count : 0,
        total : 0,   
}